name: Compile-Linux-Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install-Dependences
        run: |
          sudo apt-get update && sudo apt-get upgrade && sudo apt-get install wget exuberant-ctags libncurses5-dev curl git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison gcc make cmake g++ xz-utils zstd dwarves aria2

      - name: Download-And-Unpacked
        run: |
          sudo aria2c -x 16 -s 32 https://gitlab.com/msm8998-mainline/linux/-/archive/mainline/6.1/linux-mainline-6.1.tar.gz &>/dev/null
          sudo tar -xvf linux-mainline-6.1.tar.gz &> /dev/null
          sudo cp config linux-mainline-6.1
          sudo rm -rf linux-mainline-6.1.tar.gz
          
      - name: Complie-The-Kernel
        run: |
          cd linux-mainline-6.1
          sudo mv config .config
          sudo make clean
          sudo make -j$(nproc)
          cd ..
          sudo tar -cvpzf linux-mainline-6.1.tgz linux-mainline-6.1/

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: linux-mainline-6.1
          name: linux-mainline-6.1.tgz
          body: Manually build the android kernel.
          draft: false
          prerelease: false
          files: ./kernelfiles/linux-${{ inputs.version }}/buildpackages/*
